// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: customers.sql

package repository

import (
	"context"
)

const getCustomerById = `-- name: GetCustomerById :one
SELECT id, phone, first_name, last_name, location, preferred_product, created_at, updated_at FROM customers WHERE id = $1
`

func (q *Queries) GetCustomerById(ctx context.Context, customerID int64) (*Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerById, customerID)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.FirstName,
		&i.LastName,
		&i.Location,
		&i.PreferredProduct,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
