// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Campaign struct {
	ID           int64            `json:"id"`
	Name         string           `json:"name"`
	Channel      string           `json:"channel"`
	Status       string           `json:"status"`
	BaseTemplate string           `json:"base_template"`
	ScheduledAt  pgtype.Timestamp `json:"scheduled_at"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

type Customer struct {
	ID               int64            `json:"id"`
	Phone            string           `json:"phone"`
	FirstName        pgtype.Text      `json:"first_name"`
	LastName         pgtype.Text      `json:"last_name"`
	Location         pgtype.Text      `json:"location"`
	PreferredProduct pgtype.Text      `json:"preferred_product"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	UpdatedAt        pgtype.Timestamp `json:"updated_at"`
}

type OutboundMessage struct {
	ID              int64            `json:"id"`
	CampaignID      int64            `json:"campaign_id"`
	CustomerID      int64            `json:"customer_id"`
	Status          string           `json:"status"`
	RenderedContent string           `json:"rendered_content"`
	LastError       pgtype.Text      `json:"last_error"`
	RetryCount      int32            `json:"retry_count"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
}
