// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbound_messages.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOutboundMessage = `-- name: CreateOutboundMessage :one
INSERT INTO outbound_messages (campaign_id, customer_id, status, rendered_content, last_error, retry_count)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, campaign_id, customer_id, status, rendered_content, last_error, retry_count, created_at, updated_at
`

type CreateOutboundMessageParams struct {
	CampaignID      int64       `json:"campaign_id"`
	CustomerID      int64       `json:"customer_id"`
	Status          string      `json:"status"`
	RenderedContent string      `json:"rendered_content"`
	LastError       pgtype.Text `json:"last_error"`
	RetryCount      int32       `json:"retry_count"`
}

func (q *Queries) CreateOutboundMessage(ctx context.Context, arg *CreateOutboundMessageParams) (*OutboundMessage, error) {
	row := q.db.QueryRow(ctx, createOutboundMessage,
		arg.CampaignID,
		arg.CustomerID,
		arg.Status,
		arg.RenderedContent,
		arg.LastError,
		arg.RetryCount,
	)
	var i OutboundMessage
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.CustomerID,
		&i.Status,
		&i.RenderedContent,
		&i.LastError,
		&i.RetryCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
